"""empty message

Revision ID: 11fd54e789fc
Revises: 419085a7d0d7
Create Date: 2019-08-04 08:50:39.293091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11fd54e789fc'
down_revision = '419085a7d0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
