"""empty message

Revision ID: 3543b9c7c141
Revises: 480b7bd40d41
Create Date: 2019-08-05 22:15:33.745038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3543b9c7c141'
down_revision = '480b7bd40d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_log_ibfk_1', 'category_log', type_='foreignkey')
    op.drop_constraint('category_log_ibfk_2', 'category_log', type_='foreignkey')
    op.create_foreign_key(None, 'category_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'category_log', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_log', type_='foreignkey')
    op.drop_constraint(None, 'category_log', type_='foreignkey')
    op.create_foreign_key('category_log_ibfk_2', 'category_log', 'user', ['user_id'], ['id'])
    op.create_foreign_key('category_log_ibfk_1', 'category_log', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
