"""empty message

Revision ID: 6dd99af22f8d
Revises: b4a35ca33302
Create Date: 2019-07-05 13:36:09.641383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dd99af22f8d'
down_revision = 'b4a35ca33302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_token', 'expired_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_token', 'expired_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
