"""empty message

Revision ID: 77ae8ac47f24
Revises: ceee874a7c5f
Create Date: 2019-08-04 17:18:53.299489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77ae8ac47f24'
down_revision = 'ceee874a7c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role', sa.String(length=256), nullable=True))
    op.drop_column('role', 'role_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_name', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('role', 'role')
    # ### end Alembic commands ###
