"""empty message

Revision ID: 8da4a8849b35
Revises: 11932e3fb2ff
Create Date: 2019-08-01 09:22:02.912101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da4a8849b35'
down_revision = '11932e3fb2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('fullname', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'fullname')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
