"""empty message

Revision ID: 999a2ba4c556
Revises: 33d3f404344c
Create Date: 2019-08-08 10:07:01.672177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999a2ba4c556'
down_revision = '33d3f404344c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_log_ibfk_1', 'book_log', type_='foreignkey')
    op.create_foreign_key(None, 'book_log', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_log', type_='foreignkey')
    op.create_foreign_key('book_log_ibfk_1', 'book_log', 'category', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
