"""empty message

Revision ID: b4a35ca33302
Revises: 54c363e4e76a
Create Date: 2019-07-04 00:22:55.904455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4a35ca33302'
down_revision = '54c363e4e76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_token', 'expired_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_token', 'expired_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
