"""empty message

Revision ID: c788b3c222ad
Revises: 
Create Date: 2019-08-08 21:52:23.634877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c788b3c222ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('author', sa.Text(collation='utf8mb4_general_ci', _expect_unicode=True), nullable=True),
    sa.Column('description', sa.Text(collation='utf8mb4_general_ci', _expect_unicode=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('star', sa.SmallInteger(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('description', sa.Text(collation='utf8mb4_general_ci', _expect_unicode=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=255, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=256, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('email', sa.String(length=128, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('password_hash', sa.Text(collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('expired_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_token_confirm', sa.Text(collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('email', sa.String(length=128, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('fullname', sa.String(length=128, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.Text(collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('time_unlock', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('book_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('log_name', sa.Enum('CREATED', 'UPDATED', name='logaction'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_book',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE')
    )
    op.create_table('category_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('log_name', sa.Enum('CREATED', 'UPDATED', name='logaction'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_pass_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('password_hash', sa.Text(collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_wrong_password',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('social_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('social_name', sa.Enum('FACEBOOK', 'GOOGLE', name='socialname'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_name', sa.String(length=256, collation='utf8mb4_general_ci', _expect_unicode=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('user_action')
    op.drop_table('social_login')
    op.drop_table('history_wrong_password')
    op.drop_table('history_pass_change')
    op.drop_table('category_log')
    op.drop_table('category_book')
    op.drop_table('book_log')
    op.drop_table('user')
    op.drop_table('signup_request')
    op.drop_table('role')
    op.drop_table('revoked_token')
    op.drop_table('category')
    op.drop_table('book')
    # ### end Alembic commands ###
