"""empty message

Revision ID: ceee874a7c5f
Revises: a6ac9505f459
Create Date: 2019-08-04 10:24:22.697302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ceee874a7c5f'
down_revision = 'a6ac9505f459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_name', sa.String(length=256), nullable=True))
    op.drop_column('role', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', mysql.TEXT(), nullable=True))
    op.drop_column('role', 'role_name')
    # ### end Alembic commands ###
