"""empty message

Revision ID: f3519a2f8bcc
Revises: 77ae8ac47f24
Create Date: 2019-08-04 17:20:04.892797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3519a2f8bcc'
down_revision = '77ae8ac47f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_name', sa.String(length=256), nullable=True))
    op.drop_column('role', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('role', 'role_name')
    # ### end Alembic commands ###
